export const PRODUCT_ASSOCIATION_REQUEST = 'PRODUCT_ASSOCIATION_REQUEST';
export const PRODUCT_ASSOCIATION_SUCCESS = 'PRODUCT_ASSOCIATION_SUCCESS';
export const PRODUCT_ASSOCIATION_FAIL = 'PRODUCT_ASSOCIATION_FAIL';