export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST';
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL';


export const CONFIRM_MESSAE_READ_REQUEST = 'CONFIRM_MESSAE_READ_REQUEST';
export const CONFIRM_MESSAE_READ_SUCCESS = 'CONFIRM_MESSAE_READ_SUCCESS';
export const CONFIRM_MESSAE_READ_FAIL = 'CONFIRM_MESSAE_READ_FAIL';