export const PREMIUM_LIST_REQUEST = 'PREMIUM_LIST_REQUEST';
export const PREMIUM_LIST_SUCCESS = 'PREMIUM_LIST_SUCCESS';
export const PREMIUM_LIST_FAIL = 'PREMIUM_LIST_FAIL';

export const CONFIRM_PREMIUM_REQUEST = 'CONFIRM_PREMIUM_REQUEST';
export const CONFIRM_PREMIUM_SUCCESS = 'CONFIRM_PREMIUM_SUCCESS';
export const CONFIRM_PREMIUM_FAIL = 'CONFIRM_PREMIUM_FAIL';

export const CONFIRM_BASIC_REQUEST = 'CONFIRM_BASIC_REQUEST';
export const CONFIRM_BASIC_SUCCESS = 'CONFIRM_BASIC_SUCCESS';
export const CONFIRM_BASIC_FAIL = 'CONFIRM_BASIC_FAIL';

export const CONFIRM_READ_REQUEST = 'CONFIRM_READ_REQUEST';
export const CONFIRM_READ_SUCCESS = 'CONFIRM_READ_SUCCESS';
export const CONFIRM_READ_FAIL = 'CONFIRM_READ_FAIL';
