export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const ADMIN_LIST_REQUEST = 'ADMIN_LIST_REQUEST';
export const ADMIN_LIST_SUCCESS = 'ADMIN_LIST_SUCCESS';
export const ADMIN_LIST_FAIL = 'ADMIN_LIST_FAIL';

export const USERFILE_LIST_REQUEST = 'USERFILE_LIST_REQUEST';
export const USERFILE_LIST_SUCCESS = 'USERFILE_LIST_SUCCESS';
export const USERFILE_LIST_FAIL = 'USERFILE_LIST_FAIL';

export const ADMIN_REFRESH_REQUEST = 'ADMIN_REFRESH_REQUEST';
export const ADMIN_REFRESH_SUCCESS = 'ADMIN_REFRESH_SUCCESS';
export const ADMIN_REFRESH_FAIL = 'ADMIN_REFRESH_FAIL';

export const CONFIRM_DEACTIVATE_USER_REQUEST = 'CONFIRM_DEACTIVATE_USER_REQUEST';
export const CONFIRM_DEACTIVATE_USER_SUCCESS = 'CONFIRM_DEACTIVATE_USER_SUCCESS';
export const CONFIRM_DEACTIVATE_USER_FAIL = 'CONFIRM_DEACTIVATE_USER_FAIL';

export const CONFIRM_ACTIVATE_USER_REQUEST = 'CONFIRM_ACTIVATE_USER_REQUEST';
export const CONFIRM_ACTIVATE_USER_SUCCESS = 'CONFIRM_ACTIVATE_USER_SUCCESS';
export const CONFIRM_ACTIVATE_USER_FAIL = 'CONFIRM_ACTIVATE_USER_FAIL';

export const CONFIRM_DEACTIVATE_ADMIN_REQUEST = 'CONFIRM_DEACTIVATE_ADMIN_REQUEST';
export const CONFIRM_DEACTIVATE_ADMIN_SUCCESS = 'CONFIRM_DEACTIVATE_ADMIN_SUCCESS';
export const CONFIRM_DEACTIVATE_ADMIN_FAIL = 'CONFIRM_DEACTIVATE_ADMIN_FAIL';

export const CONFIRM_ACTIVATE_ADMIN_REQUEST = 'CONFIRM_ACTIVATE_ADMIN_REQUEST';
export const CONFIRM_ACTIVATE_ADMIN_SUCCESS = 'CONFIRM_ACTIVATE_ADMIN_SUCCESS';
export const CONFIRM_ACTIVATE_ADMIN_FAIL = 'CONFIRM_ACTIVATE_ADMIN_FAIL';